import pandas as pd     
import streamlit as st

st.markdown('# MÊS DE FEVEREIRO')


df_fev = pd.read_excel('fusex.xlsx', sheet_name='FEV 23')


df2 = df_fev.drop(columns=['ENTRADA SECRETARIA', 'SAÍDA  SECRETÁRIA', 'STATUS SEC', 'DIAS',
         'ENTRADA / DIVISAO DE MEDICINA ', 'SAIDA / DIVISAO DE MEDICINA',
         'LINK DO PROC', 'TELEFONE BENEFICIÁRIO', 'EMAIL BENEFICIÁRIO',
         'PREC-CP', 'ENTRADA  AUDITORIA', 'AUDITORIA ENFERMAGEM', 'ENTRADA ENFERMAGEM',
         'SAÍDA ENFERMAGEM', 'DIAS.1', 'AUDITORIA MÉDICA', 'ENTRADA MÉDICA', 'SAÍDA MÉDICA',
         'DIAS.2', 'STATUS DA SOLICITAÇÃO', 'DATA DA PENDÊNCIA', 'RESPONSÁVEL PELA SOLUÇÃO',
         'OBSERVAÇÕES', 'GUIA HM', 'GUIA ANEST', 'GUIA OPME', 'GUIA HOSP', 'Nº DA AUTZ',
         'ENTREGA SECRETARIA', 'ENTREGA BENEFICIÁRIO', 'OBSERVAÇÃO SECRETARIA', 'TEMPO TOTAL PROCESSO'])